# Generated by Django 6.0.7 on 2026-07-24 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('address_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('neighborhood', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rn', models.CharField(max_length=7)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
