# Generated by Django 6.0.7 on 2026-07-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Customer',
        ),
    ]
