# Generated by Django 6.0.7 on 2026-07-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_person_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Staff',
        ),
    ]
