# Generated by Django 6.0.7 on 2026-08-26 14:29

import profiles.staff.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_admin_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='rn',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=profiles.staff.models.StaffId(default=10001),
            preserve_default=False,
        ),
    ]
