# Generated by Django 6.0.7 on 2026-08-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_staff_rn_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
