# Generated by Django 6.0.7 on 2026-08-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_customer_user_uuid_staff_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
